CREATE TABLE public.sec_users (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp NOT NULL,
	updated_at timestamp NULL,
	"version" numeric NOT NULL DEFAULT 0,
	username varchar(50) NOT NULL,
	email varchar(70) NOT NULL,
	"password" varchar(100) NOT NULL,
	avatar text NULL,
	status varchar(3) NOT NULL DEFAULT 'ACT'::character varying,
	CONSTRAINT sec_users_email_key UNIQUE (email),
	CONSTRAINT sec_users_username_key UNIQUE (username),
	CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE public.sec_roles (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(50) NOT NULL,
	status varchar(3) NOT NULL DEFAULT 'ACT'::character varying,
	CONSTRAINT roles_pkey PRIMARY KEY (id),
	CONSTRAINT sec_roles_name_key UNIQUE (name)
);

CREATE TABLE public.sec_user_rol (
	user_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	rol_id int8 NOT NULL,
	CONSTRAINT sec_user_rol_pkey PRIMARY KEY (user_id, rol_id),
	CONSTRAINT fk_user_rol FOREIGN KEY (user_id) REFERENCES public.sec_users(id),
	CONSTRAINT fk_rol_user FOREIGN KEY (rol_id) REFERENCES public.sec_roles(id)
);

INSERT INTO sec_roles (name, status) VALUES
  ('ROLE_ADMIN', 'ACT'),
  ('ROLE_CUSTOMER', 'ACT');

INSERT INTO sec_users (created_at, updated_at, "username", email, "password", status)
	   VALUES(now(), now(), 'Administrador', 'diego1503bsc@gmail.com',
	  '$2a$10$gRde6y2LNyQwT6rVqem3qugYCqKDwgsqP/N1D2DHWr7tO2jupzLtG', 'ACT'::character varying);

INSERT INTO public.sec_user_rol (user_id, rol_id) values
			((select id from sec_users where username = 'Administrador'),
			 (select id from sec_roles where name = 'ROLE_ADMIN'));

