CREATE TABLE public.brands (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(50) NOT NULL,
	status varchar(3) NOT NULL DEFAULT 'ACT'::character varying,
	CONSTRAINT brands_pkey PRIMARY KEY (id),
	CONSTRAINT brands_name_key UNIQUE (name)
);

CREATE TABLE public.cars (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp NOT NULL,
	updated_at timestamp NULL,
	"version" numeric NOT NULL DEFAULT 0,
	name varchar(50) NOT NULL,
	price int8,
	description text NOT NULL,
	kilometres int8 NOT NULL,
	year_car int4 NOT NULL,
	image text NULL,
	status varchar(3) NOT NULL DEFAULT 'NEW'::character varying,
	brand_id int4,
	CONSTRAINT cars_pkey PRIMARY KEY (id),
	CONSTRAINT fk_car_brand FOREIGN KEY (brand_id) REFERENCES public.brands(id)
);

CREATE TABLE public.catalogs (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(50) NOT NULL,
	status varchar(3) NOT NULL DEFAULT 'ACT'::character varying,
	CONSTRAINT catalogs_pkey PRIMARY KEY (id),
	CONSTRAINT catalogs_name_key UNIQUE (name)
);

CREATE TABLE public.catalogs_cars (
	car_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	catalog_id int8 NOT NULL,
	CONSTRAINT car_catalog_pkey PRIMARY KEY (car_id, catalog_id),
	CONSTRAINT fk_catalog_car FOREIGN KEY (car_id) REFERENCES public.cars(id),
	CONSTRAINT fk_car_catalog FOREIGN KEY (catalog_id) REFERENCES public.catalogs(id)
);